### ISSUE TITLE
As a developer I want the GitHub environment to be set up completely so everyone can work on the project together as efficient as possible.

### ISSUE THREAD

**Issue by awqfrxx** [SDG-Tool-T10/SDG-Tool#1]
As a developer I want the GitHub environment to be set up completely so everyone can work on the project together as efficient as possible.

**Comment by awqfrxx** [comment]
Almost everything seems to work. Just need to figure out how to work with different branches 😄

**Comment by awqfrxx** [comment]
Add correct .gitignore file and different branches for every team member.

**Comment by Koreyoshi159** [comment]
Acceptance criteria:
Everyone can access Git repo.
Everyone can manage the repo.
