### ISSUE TITLE
As a developer I want to setup a meeting with the client so that we'll have a better view on the project

### ISSUE THREAD

**Issue by awqfrxx** [SDG-Tool-T10/SDG-Tool#3]
As a developer and on-site customer I want to plan appointments with our client on time so we can prepare for these events.

**Comment by awqfrxx** [comment]
Contact with the client was made and the only available time was Friday the 19th.
Contact still on-going. Need more clarification

**Comment by koenhamstra** [comment]
Appointment is made for March 19th at 13.00 hour
